CLIP: clip::DataArray Class Reference
clip::DataArray Class Reference
Manages all host and device memory allocations for the CLIP LBM solver.
Classes
struct deviceDataArray
Struct holding all device-side (GPU) pointers for LBM fields.
struct hostDataArray
Struct holding all host-side (CPU) pointers for LBM fields.
Public Member Functions
DataArray (const InputData &idata, const Domain &domain, const Boundary &boundary)
Construct a DataArray manager with simulation inputs and domain info.
~DataArray ()
Destructor.
template<typename T >
void allocateOnDevice (T *&devPtr, const std::string &name, CLIP_UINT ndof=SCALAR_FIELD)
Allocates device memory on GPU for a given pointer.
template<typename T >
void allocateOnHost (T *&hostPtr, const std::string &name, CLIP_UINT ndof=SCALAR_FIELD)
Allocates host memory (CPU) for a given pointer.
template<typename T >
void copyToDevice (T *&devPtr, const T *hostPtr, const std::string &name, CLIP_UINT ndof=SCALAR_FIELD)
Copies data from host to device.
template<typename T >
void copyFromDevice (T *&hostPtr, const T *devPtr, const std::string &name, CLIP_UINT ndof=SCALAR_FIELD)
Copies data from device to host.
template<typename T >
void copyDevice (T *&destPtr, const T *sourcePtr, const std::string &name, CLIP_UINT ndof=SCALAR_FIELD)
Copies data between device pointers.
template<typename T , size_t N>
void symbolOnDevice (const T(&symbol)[N], const T *hostPtr, const std::string &name)
Copies a constant array to device symbol memory.
template<typename T >
void symbolOnDevice (const T &symbol, const T *hostPtr, const std::string &name)
Copies a single object to device symbol memory.
template<typename T >
void writeHostToFile (const T *hostPtr, const std::string &filename, CLIP_UINT size)
Writes a host-side array to a binary file.
template<typename T >
void readHostFromFile (T *hostPtr, const std::string &filename, CLIP_UINT size)
Reads a host-side array from a binary file.
void createVectors ()
Allocate and initialize all host/device field arrays.
void updateDevice ()
Copy all host-side fields to device.
void updateHost ()
Copy all device-side fields to host.
Public Attributes
dim3 dimBlock
CUDA thread/block configuration for kernels.
dim3 dimGrid
deviceDataArray deviceDA
hostDataArray hostDA
Detailed Description
Manages all host and device memory allocations for the CLIP LBM solver.
This class handles allocation, transfer, and file I/O for all primary simulation fields used in the Lattice Boltzmann Method (LBM), including velocity, pressure, and distribution functions.
Definition at line 62 of file DataArray.cuh.
Constructor & Destructor Documentation
DataArray()
clip::DataArray::DataArray (const InputData & idata, const Domain & domain, const Boundary & boundary) explicit
Construct a DataArray manager with simulation inputs and domain info.
Parameters
idata Input parameters
domain Simulation domain object
boundary Boundary condition object
Definition at line 23 of file DataArray.cu.
References dimBlock, IDX_X, IDX_Y, IDX_Z, and clip::Domain::info.
~DataArray()
clip::DataArray::~DataArray ()
Destructor.
Definition at line 48 of file DataArray.cu.
References SAFE_CUDA_FREE.
Member Function Documentation
allocateOnDevice()
template<typename T > void clip::DataArray::allocateOnDevice (T *& devPtr, const std::string & name, CLIP_UINT ndof = SCALAR_FIELD) inline
Allocates device memory on GPU for a given pointer.
Template Parameters
T Data type
Parameters
[out] devPtr Pointer to be allocated on device
name Debugging label
ndof Number of degrees of freedom (default = scalar)
Definition at line 86 of file DataArray.cuh.
References cudaCheckErrors, and clip::Domain::domainSize.
Referenced by createVectors().
allocateOnHost()
template<typename T > void clip::DataArray::allocateOnHost (T *& hostPtr, const std::string & name, CLIP_UINT ndof = SCALAR_FIELD) inline
Allocates host memory (CPU) for a given pointer.
Template Parameters
T Data type
Parameters
[out] hostPtr Pointer to be allocated on host
name Debugging label
ndof Number of degrees of freedom
Definition at line 101 of file DataArray.cuh.
References clip::Domain::domainSize.
Referenced by createVectors().
copyDevice()
template<typename T > void clip::DataArray::copyDevice (T *& destPtr, const T * sourcePtr, const std::string & name, CLIP_UINT ndof = SCALAR_FIELD) inline
Copies data between device pointers.
Template Parameters
T Data type
Parameters
[out] destPtr Destination device pointer
sourcePtr Source device pointer
name Debug label
ndof Number of degrees of freedom
Definition at line 150 of file DataArray.cuh.
References cudaCheckErrors, and clip::Domain::domainSize.
copyFromDevice()
template<typename T > void clip::DataArray::copyFromDevice (T *& hostPtr, const T * devPtr, const std::string & name, CLIP_UINT ndof = SCALAR_FIELD) inline
Copies data from device to host.
Template Parameters
T Data type
Parameters
[out] hostPtr Host pointer destination
devPtr Device source pointer
name Debug label
ndof Number of degrees of freedom
Definition at line 135 of file DataArray.cuh.
References cudaCheckErrors, and clip::Domain::domainSize.
Referenced by updateHost().
copyToDevice()
template<typename T > void clip::DataArray::copyToDevice (T *& devPtr, const T * hostPtr, const std::string & name, CLIP_UINT ndof = SCALAR_FIELD) inline
Copies data from host to device.
Template Parameters
T Data type
Parameters
[out] devPtr Device pointer destination
hostPtr Host source pointer
name Debug label
ndof Number of degrees of freedom
Definition at line 120 of file DataArray.cuh.
References cudaCheckErrors, and clip::Domain::domainSize.
Referenced by updateDevice().
createVectors()
void clip::DataArray::createVectors ()
Allocate and initialize all host/device field arrays.
Definition at line 79 of file DataArray.cu.
References allocateOnDevice(), allocateOnHost(), clip::Boundary::isFreeConvect, SCALAR_FIELD, and clip::Logger::Success().
readHostFromFile()
template<typename T > void clip::DataArray::readHostFromFile (T * hostPtr, const std::string & filename, CLIP_UINT size) inline
Reads a host-side array from a binary file.
Template Parameters
T Data type
Parameters
[out] hostPtr Pointer to write into
filename Input file path
size Number of elements
Definition at line 215 of file DataArray.cuh.
References clip::Logger::Error().
symbolOnDevice() [1/2]
template<typename T > void clip::DataArray::symbolOnDevice (const T & symbol, const T * hostPtr, const std::string & name) inline
Copies a single object to device symbol memory.
Template Parameters
T Data type
Parameters
symbol Symbol reference
hostPtr Source data
name Debug label
Definition at line 180 of file DataArray.cuh.
References cudaCheckErrors.
symbolOnDevice() [2/2]
template<typename T , size_t N> void clip::DataArray::symbolOnDevice (const T(&) symbol[N], const T * hostPtr, const std::string & name) inline
Copies a constant array to device symbol memory.
Template Parameters
T Data type
N Array size
Parameters
symbol Symbol destination
hostPtr Source data
name Debug label
Definition at line 165 of file DataArray.cuh.
References cudaCheckErrors.
updateDevice()
void clip::DataArray::updateDevice ()
Copy all host-side fields to device.
Definition at line 124 of file DataArray.cu.
References copyToDevice(), and SCALAR_FIELD.
updateHost()
void clip::DataArray::updateHost ()
Copy all device-side fields to host.
Definition at line 131 of file DataArray.cu.
References copyFromDevice(), and SCALAR_FIELD.
Referenced by clip::VTSwriter::writeToFile().
writeHostToFile()
template<typename T > void clip::DataArray::writeHostToFile (const T * hostPtr, const std::string & filename, CLIP_UINT size) inline
Writes a host-side array to a binary file.
Template Parameters
T Data type
Parameters
hostPtr Pointer to data
filename Output file path
size Number of elements
Definition at line 195 of file DataArray.cuh.
References clip::Logger::Error().
Member Data Documentation
deviceDA
deviceDataArray clip::DataArray::deviceDA
Definition at line 271 of file DataArray.cuh.
dimBlock
dim3 clip::DataArray::dimBlock
CUDA thread/block configuration for kernels.
Definition at line 229 of file DataArray.cuh.
Referenced by DataArray(), clip::NSAllen::NSAllen(), and clip::Solver::Solver().
dimGrid
dim3 clip::DataArray::dimGrid
Definition at line 229 of file DataArray.cuh.
hostDA
hostDataArray clip::DataArray::hostDA
Definition at line 272 of file DataArray.cuh.
The documentation for this class was generated from the following files:
/home/runner/work/CLIP/CLIP/include/data/DataArray.cuh
/home/runner/work/CLIP/CLIP/src/data/DataArray.cu