CLIP: clip::Domain Class Reference
clip::Domain Class Reference
Represents the simulation domain and provides indexing and boundary utility functions.
Classes
struct DomainInfo
Holds global domain metadata, including extent and boundaries.
Public Member Functions
Domain (const InputData &idata)
Construct a Domain object using input parameters.
Static Public Member Functions
template<CLIP_UINT ndof = 1>
__host__ __device__ static __forceinline__ CLIP_UINT getIndex (const DomainInfo &domain, CLIP_UINT i, CLIP_UINT j, CLIP_UINT k, CLIP_UINT dof=SCALAR)
Computes a flattened 1D index for multi-DOF data.
template<CLIP_UINT dim, bool ghosted = false>
__device__ static __forceinline__ bool isInside (const DomainInfo &domain, CLIP_INT i, CLIP_INT j, CLIP_INT k=0)
Determines if a node lies within the domain bounds.
Public Attributes
DomainInfo info
Contains extent and boundary indices.
CLIP_UINT domainSize
Total number of grid points (flattened)
Protected Attributes
dim3 dimBlock
dim3 dimGrid
CUDA kernel launch configuration.
const InputData * m_idata
Reference to input parameters.
Detailed Description
Represents the simulation domain and provides indexing and boundary utility functions.
This class stores global indexing info and offers device-safe indexing logic. It supports both ghosted and non-ghosted domain regions, and works for both 2D and 3D setups.
Definition at line 30 of file Domain.cuh.
Constructor & Destructor Documentation
Domain()
clip::Domain::Domain (const InputData & idata) explicit
Construct a Domain object using input parameters.
Parameters
idata Reference to input data (e.g., domain dimensions, ghost layers).
Definition at line 22 of file Domain.cu.
References domainSize, IDX_X, IDX_Y, IDX_Z, info, m_idata, and clip::InputData::params.
Member Function Documentation
getIndex()
template<CLIP_UINT ndof = 1> __host__ __device__ static __forceinline__ CLIP_UINT clip::Domain::getIndex (const DomainInfo & domain, CLIP_UINT i, CLIP_UINT j, CLIP_UINT k, CLIP_UINT dof = SCALAR) inline static
Computes a flattened 1D index for multi-DOF data.
Template Parameters
ndof Number of degrees of freedom (e.g., scalar = 1, vector = 2 or 3).
Parameters
domain DomainInfo struct
i Index in X direction
j Index in Y direction
k Index in Z direction
dof Degree of freedom offset
Returns
Flattened global index for accessing a field
Definition at line 64 of file Domain.cuh.
References IDX_Y, and IDX_Z.
Referenced by clip::Chemical_Potential(), clip::NSAllen::initialCondition(), clip::Isotropic_Gradient(), clip::JetBoundary(), clip::kernelCollisionMRTf(), clip::kernelCollisionMRTg(), clip::kernelFreeConvect(), clip::kernelFullBouncBack(), clip::kernelHalfBounceBack(), clip::KernelInitializeDistributions(), clip::kernelMacroscopicf(), clip::kernelMacroscopicg(), clip::kernelMirrorBoundary(), clip::kernelNeumann(), clip::kernelPeriodicBoundary(), clip::kernelStreaming(), clip::normal_FD(), and clip::sumReductionKernel().
isInside()
template<CLIP_UINT dim, bool ghosted = false> __device__ static __forceinline__ bool clip::Domain::isInside (const DomainInfo & domain, CLIP_INT i, CLIP_INT j, CLIP_INT k = 0) inline static
Determines if a node lies within the domain bounds.
Template Parameters
dim Spatial dimensionality (2 or 3)
ghosted If true, does not include ghost cell layers
Parameters
domain DomainInfo struct
i Index in X
j Index in Y
k Index in Z (optional for 2D)
Returns
true if the node is inside the domain
Definition at line 82 of file Domain.cuh.
References IDX_X, IDX_Y, and IDX_Z.
Member Data Documentation
dimBlock
dim3 clip::Domain::dimBlock protected
Definition at line 110 of file Domain.cuh.
dimGrid
dim3 clip::Domain::dimGrid protected
CUDA kernel launch configuration.
Definition at line 110 of file Domain.cuh.
domainSize
CLIP_UINT clip::Domain::domainSize
Total number of grid points (flattened)
Definition at line 104 of file Domain.cuh.
Referenced by clip::DataArray::allocateOnDevice(), clip::DataArray::allocateOnHost(), clip::DataArray::copyDevice(), clip::DataArray::copyFromDevice(), clip::DataArray::copyToDevice(), Domain(), and clip::Reporter::print().
info
DomainInfo clip::Domain::info
Contains extent and boundary indices.
Definition at line 103 of file Domain.cuh.
Referenced by clip::DataArray::DataArray(), Domain(), clip::NSAllen::NSAllen(), and clip::Solver::Solver().
m_idata
const InputData* clip::Domain::m_idata protected
Reference to input parameters.
Definition at line 111 of file Domain.cuh.
Referenced by Domain().
The documentation for this class was generated from the following files:
/home/runner/work/CLIP/CLIP/include/domain/Domain.cuh
/home/runner/work/CLIP/CLIP/src/domain/Domain.cu