CLIP: clip::TimeInfo Class Reference
clip::TimeInfo Class Reference
Handles time step tracking and advancement for LBM simulations.
Classes
struct simInfo
Holds simulation time-related quantities.
Public Member Functions
TimeInfo (InputData idata)
Constructs a TimeInfo manager using simulation input parameters.
int getCurrentStep () const
Returns the current time step index.
double getCurrentTime () const
Returns the current simulation time.
double getEndTime () const
Returns the final simulation time (tFinal) from input.
double getFinalStep () const
Returns the maximum number of time steps (finalStep) from input.
void increment ()
Advances the simulation by one time step.
void setTimeStep (double dt)
Sets the time step value.
simInfo & getSimInfo ()
Returns a reference to the internal simInfo struct.
const simInfo & getSimInfo () const
Returns a const reference to the internal simInfo struct.
Detailed Description
Handles time step tracking and advancement for LBM simulations.
The TimeInfo class tracks the simulation clock, time step, and step count, and provides an interface for advancing or querying the simulation state.
Definition at line 31 of file TimeInfo.cuh.
Constructor & Destructor Documentation
TimeInfo()
clip::TimeInfo::TimeInfo (InputData idata) explicit
Constructs a TimeInfo manager using simulation input parameters.
Constructor for TimeInfo.
Parameters
idata The input configuration object
idata InputData object containing simulation parameters.
Definition at line 28 of file TimeInfo.cu.
Member Function Documentation
getCurrentStep()
int clip::TimeInfo::getCurrentStep () const
Returns the current time step index.
Returns the current simulation step.
Returns
Current step as an integer.
Definition at line 36 of file TimeInfo.cu.
References clip::TimeInfo::simInfo::currentStep.
Referenced by clip::Reporter::print(), clip::CheckPointer::save(), and clip::VTSwriter::writeToFile().
getCurrentTime()
double clip::TimeInfo::getCurrentTime () const
Returns the current simulation time.
Returns the current simulation time based on time step and step count.
Returns
Current physical time.
Definition at line 46 of file TimeInfo.cu.
References clip::TimeInfo::simInfo::currentStep, and clip::TimeInfo::simInfo::dt.
getFinalStep()
double clip::TimeInfo::getFinalStep () const
Returns the maximum number of time steps (finalStep) from input.
Returns the user-specified final step from the input configuration.
Returns
Final step as an integer.
Definition at line 74 of file TimeInfo.cu.
References clip::InputData::params.
getSimInfo() [1/2]
TimeInfo::simInfo & clip::TimeInfo::getSimInfo ()
Returns a reference to the internal simInfo struct.
Returns a reference to the internal simInfo structure.
Returns
Reference to mutable simInfo.
Definition at line 84 of file TimeInfo.cu.
getSimInfo() [2/2]
const TimeInfo::simInfo & clip::TimeInfo::getSimInfo () const
Returns a const reference to the internal simInfo struct.
Returns a const reference to the internal simInfo structure.
Returns
Const reference to simInfo.
Definition at line 94 of file TimeInfo.cu.
increment()
void clip::TimeInfo::increment ()
Advances the simulation by one time step.
Increments the current simulation step counter by one.
Definition at line 64 of file TimeInfo.cu.
References clip::TimeInfo::simInfo::currentStep.
setTimeStep()
void clip::TimeInfo::setTimeStep (double dt)
Sets the time step value.
Sets the simulation time step (dt).
Parameters
dt The time step size
dt The desired time step.
Definition at line 54 of file TimeInfo.cu.
References clip::TimeInfo::simInfo::dt, and clip::TimeInfo::simInfo::dtIsSet.
The documentation for this class was generated from the following files:
/home/runner/work/CLIP/CLIP/include/utils/TimeInfo.cuh
/home/runner/work/CLIP/CLIP/src/utils/TimeInfo.cu