CLIP: clip::WMRT Class Reference
clip::WMRT Class Reference
Weighted MRT conversion and utility definitions for Lattice Boltzmann Method.
Classes
struct slipWallBCMap
Mapping of slip wall boundary directions for specular reflection.
struct velocityBCMap
Mapping of velocity inlet/outlet directions for custom boundary handling.
struct wallBCMap
Mapping of wall boundary directions for bounce-back in 2D/3D.
struct wallCornerBCMap
struct WMRTvelSet
Defines the discrete velocity set and weights for the WMRT model.
Public Member Functions
WMRT ()
Constructor.
virtual ~WMRT ()
Destructor.
Static Public Member Functions
__device__ static __forceinline__ void convertD2Q9Weighted (const CLIP_REAL in[9], CLIP_REAL out[9])
Converts a D2Q9 distribution function to weighted moment space.
__device__ static __forceinline__ void reconvertD2Q9Weighted (const CLIP_REAL in[9], CLIP_REAL out[9])
Reconstructs the D2Q9 distribution function from weighted moments.
__device__ static __forceinline__ void convertD3Q19Weighted (const CLIP_REAL in[19], CLIP_REAL out[19])
Converts a D3Q19 distribution function to weighted moment space.
__device__ static __forceinline__ void reconvertD3Q19Weighted (const CLIP_REAL in[19], CLIP_REAL out[19])
Reconstructs the D3Q19 distribution function from weighted moments.
Detailed Description
Weighted MRT conversion and utility definitions for Lattice Boltzmann Method.
The WMRT class contains conversion matrices for D2Q9 and D3Q19 lattices, mapping distribution functions to weighted moment space and back. It also stores velocity set definitions and structured maps for applying different types of boundary conditions.
Definition at line 35 of file WMRT.cuh.
Constructor & Destructor Documentation
WMRT()
clip::WMRT::WMRT () inline
Constructor.
Definition at line 41 of file WMRT.cuh.
Member Function Documentation
convertD2Q9Weighted()
__device__ static __forceinline__ void clip::WMRT::convertD2Q9Weighted (const CLIP_REAL in[9], CLIP_REAL out[9]) inline static
Converts a D2Q9 distribution function to weighted moment space.
Parameters
in Input distribution function (size 9)
out Output in moment space (size 9)
Definition at line 54 of file WMRT.cuh.
Referenced by clip::kernelCollisionMRTf(), and clip::kernelMacroscopicf().
convertD3Q19Weighted()
__device__ static __forceinline__ void clip::WMRT::convertD3Q19Weighted (const CLIP_REAL in[19], CLIP_REAL out[19]) inline static
Converts a D3Q19 distribution function to weighted moment space.
Parameters
in Input distribution function (size 19)
out Output in moment space (size 19)
Definition at line 100 of file WMRT.cuh.
Referenced by clip::kernelCollisionMRTf(), and clip::kernelMacroscopicf().
reconvertD2Q9Weighted()
__device__ static __forceinline__ void clip::WMRT::reconvertD2Q9Weighted (const CLIP_REAL in[9], CLIP_REAL out[9]) inline static
Reconstructs the D2Q9 distribution function from weighted moments.
Parameters
in Input moment vector (size 9)
out Output distribution function (size 9)
Definition at line 77 of file WMRT.cuh.
Referenced by clip::kernelCollisionMRTf(), and clip::kernelMacroscopicf().
reconvertD3Q19Weighted()
__device__ static __forceinline__ void clip::WMRT::reconvertD3Q19Weighted (const CLIP_REAL in[19], CLIP_REAL out[19]) inline static
Reconstructs the D3Q19 distribution function from weighted moments.
Parameters
in Input moment vector (size 19)
out Output distribution function (size 19)
Definition at line 134 of file WMRT.cuh.
Referenced by clip::kernelCollisionMRTf(), and clip::kernelMacroscopicf().
The documentation for this class was generated from the following file:
/home/runner/work/CLIP/CLIP/include/solver/WMRT.cuh