CLIP: clip::Logger Class Reference
clip::Logger Class Reference
Utility class for formatted console output with color and severity labels.
Static Public Member Functions
static void Info (const std::string &message)
Prints an informational message to stdout.
static void Warning (const std::string &message)
Prints a warning message to stdout in yellow.
static void Error (const std::string &message, bool shouldThrow=true)
Prints an error message to stderr and optionally throws an exception.
static void Success (const std::string &message)
Prints a success message to stdout in green.
Detailed Description
Utility class for formatted console output with color and severity labels.
The Logger supports standard output levels:
Info: General status messages
Warning: Non-critical issues
Error: Fatal errors with optional exception
Success: Highlighted confirmation
Debug: Conditionally compiled developer-level diagnostics
Definition at line 36 of file Logger.cuh.
Member Function Documentation
Error()
static void clip::Logger::Error (const std::string & message, bool shouldThrow = true) inline static
Prints an error message to stderr and optionally throws an exception.
Parameters
message The error message
shouldThrow Whether to throw std::runtime_error (default = true)
Definition at line 61 of file Logger.cuh.
Referenced by clip::Reporter::print(), clip::DataArray::readHostFromFile(), and clip::DataArray::writeHostToFile().
Info()
static void clip::Logger::Info (const std::string & message) inline static
Prints an informational message to stdout.
Parameters
message The message to display
Definition at line 43 of file Logger.cuh.
Referenced by clip::Geometry::Geometry(), clip::InputData::InputData(), and clip::Reporter::print().
Success()
static void clip::Logger::Success (const std::string & message) inline static
Prints a success message to stdout in green.
Parameters
message The message to display
Definition at line 74 of file Logger.cuh.
Referenced by clip::DataArray::createVectors(), clip::Geometry::Geometry(), clip::InputData::InputData(), clip::CheckPointer::load(), and clip::CheckPointer::save().
Warning()
static void clip::Logger::Warning (const std::string & message) inline static
Prints a warning message to stdout in yellow.
Parameters
message The message to display
Definition at line 51 of file Logger.cuh.
The documentation for this class was generated from the following file:
/home/runner/work/CLIP/CLIP/include/utils/Logger.cuh