CLIP: clip::NSAllen Class Reference
clip::NSAllen Class Reference
Implements the Allen–Cahn-based Navier–Stokes solver using LBM.
Public Member Functions
NSAllen (const InputData &idata, const Domain &domain, DataArray &DA, const Boundary &boundary, const Geometry &geom)
Constructor for NSAllen solver.
~NSAllen ()
Destructor.
void solve ()
(Optional) Placeholder or user-defined inlet structure
void macroscopic ()
Computes macroscopic quantities (rho, u) from distribution functions.
void initialCondition ()
Sets the initial state of the simulation.
void deviceInitializer ()
Initializes device memory and data structures.
template<CLIP_UINT q, size_t dim>
__device__ __forceinline__ void calculateVF (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, CLIP_REAL gneq[q], CLIP_REAL fv[dim], CLIP_REAL tau, CLIP_REAL dcdx, CLIP_REAL dcdy, CLIP_REAL dcdz)
Calculates body force contributions from non-equilibrium parts of f.
Public Member Functions inherited from clip::Solver
Solver (const InputData &idata, const Domain &domain, DataArray &DA, const Boundary &boundary, const Geometry &geom)
Constructs a Solver and links input, domain, and geometry data.
virtual ~Solver ()
Destructor.
template<CLIP_UINT Q>
void periodicBoundary (CLIP_REAL *dev_a, CLIP_REAL *dev_b=nullptr)
Applies periodic boundary conditions.
template<CLIP_UINT Q, CLIP_UINT dof>
void wallBoundary (CLIP_REAL *dev_a, CLIP_REAL *dev_a_post, CLIP_REAL *dev_b=nullptr, CLIP_REAL *dev_b_post=nullptr)
Applies wall (no-slip) boundary conditions.
template<CLIP_UINT Q, CLIP_UINT dof>
void slipWallBoundary (CLIP_REAL *dev_a, CLIP_REAL *dev_a_post, CLIP_REAL *dev_b=nullptr, CLIP_REAL *dev_b_post=nullptr)
Applies slip wall boundary conditions (tangential velocity preserved).
template<CLIP_UINT Q, CLIP_UINT dof>
void freeConvectBoundary (CLIP_REAL *dev_vel, CLIP_REAL *dev_a, CLIP_REAL *dev_a_post, CLIP_REAL *dev_b=nullptr, CLIP_REAL *dev_b_post=nullptr)
Applies free convective (zero normal gradient) boundary conditions.
template<CLIP_UINT Q, CLIP_UINT dof>
void NeumannBoundary (CLIP_REAL *dev_a, CLIP_REAL *dev_b=nullptr)
Applies Neumann boundary conditions (zero gradient).
void velocityBoundary (CLIP_REAL *dev_vel, CLIP_REAL *dev_f, CLIP_REAL *dev_g)
Applies prescribed velocity boundary conditions on inlet/outlet surfaces.
void mirrorBoundary (CLIP_REAL *dev_a)
Applies mirror symmetry for scalar fields.
Static Public Member Functions
__device__ static __forceinline__ CLIP_REAL Equilibrium_new (const WMRT::WMRTvelSet velSet, CLIP_UINT q, CLIP_REAL Ux, CLIP_REAL Uy, CLIP_REAL Uz=0)
Computes equilibrium distribution for a given velocity set.
template<CLIP_UINT q, size_t dim>
__device__ static __forceinline__ void calculateVF (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, CLIP_REAL gneq[q], CLIP_REAL fv[dim], CLIP_REAL tau, CLIP_REAL dcdx, CLIP_REAL dcdy, CLIP_REAL dcdz=0)
Calculates volume fraction force (VF) terms.
Static Public Member Functions inherited from clip::Solver
__device__ static __forceinline__ CLIP_REAL Equilibrium_new (const WMRT::WMRTvelSet velSet, CLIP_UINT q, CLIP_REAL Ux, CLIP_REAL Uy, CLIP_REAL Uz)
Computes the equilibrium distribution function for WMRT-based solvers.
Additional Inherited Members
Protected Attributes inherited from clip::Solver
const Domain * m_domain
Pointer to domain geometry.
const InputData * m_idata
Input configuration.
const Boundary * m_boundary
Boundary condition data.
const Geometry * m_geom
Geometry definition.
Geometry::GeometryDevice m_geomPool
Device-side geometry info.
Domain::DomainInfo m_info
Domain metadata.
Boundary::BCTypeMap m_BCMap
Boundary condition map.
WMRT::wallBCMap m_wallBCMap
Wall boundary map (weighted MRT)
WMRT::slipWallBCMap m_slipWallBCMap
Slip wall map (weighted MRT)
WMRT::WMRTvelSet m_velSet
Lattice velocity set.
DataArray * m_DA
Data array handler.
dim3 dimGrid
dim3 dimBlock
CUDA kernel launch configuration.
Detailed Description
Implements the Allen–Cahn-based Navier–Stokes solver using LBM.
The NSAllen class integrates the Allen–Cahn phase field model with the Lattice Boltzmann Method (LBM) for simulating interfacial flows. It derives from the base Solver class and performs domain setup, equilibrium computation, volume fraction tracking, and application of custom boundary conditions.
Definition at line 38 of file NsAllen.cuh.
Constructor & Destructor Documentation
NSAllen()
clip::NSAllen::NSAllen (const InputData & idata, const Domain & domain, DataArray & DA, const Boundary & boundary, const Geometry & geom) explicit
Constructor for NSAllen solver.
Initializes fields and prepares velocity set, grid/block dimensions, and geometry pool.
Parameters
idata Simulation input configuration
domain Domain geometry and extent
DA Field data manager
boundary Boundary condition object
geom Geometry manager object
idata Simulation input data domain Computational domain DA Data storage object (host/device) boundary Boundary condition handler geom Geometry object defining physical shapes (via SDF)
Definition at line 51 of file NsAllen.cu.
References clip::DataArray::dimBlock, clip::Geometry::getDeviceStruct(), clip::Domain::info, clip::Solver::m_DA, clip::Solver::m_domain, clip::Solver::m_idata, and clip::InputData::params.
~NSAllen()
clip::NSAllen::~NSAllen ()
Destructor.
Definition at line 69 of file NsAllen.cu.
Member Function Documentation
calculateVF() [1/2]
template<CLIP_UINT q, size_t dim> __device__ __forceinline__ void clip::NSAllen::calculateVF (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, CLIP_REAL gneq[q], CLIP_REAL fv[dim], CLIP_REAL tau, CLIP_REAL dcdx, CLIP_REAL dcdy, CLIP_REAL dcdz)
Calculates body force contributions from non-equilibrium parts of f.
q Number of directions dim Spatial dimension gneq Non-equilibrium components fv Output force vector
Definition at line 107 of file NsAllen.cu.
References IDX_X, IDX_Y, and IDX_Z.
calculateVF() [2/2]
template<CLIP_UINT q, size_t dim> __device__ static __forceinline__ void clip::NSAllen::calculateVF (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, CLIP_REAL gneq[q], CLIP_REAL fv[dim], CLIP_REAL tau, CLIP_REAL dcdx, CLIP_REAL dcdy, CLIP_REAL dcdz = 0) static
Calculates volume fraction force (VF) terms.
Template Parameters
q Number of lattice directions
dim Number of spatial dimensions
Parameters
velSet Lattice velocity set
params Simulation parameters
gneq Output: nonequilibrium components
fv Output: force terms in each direction
tau Relaxation time
dcdx Phase field gradient (X)
dcdy Phase field gradient (Y)
dcdz Phase field gradient (Z, optional)
deviceInitializer()
void clip::NSAllen::deviceInitializer ()
Initializes device memory and data structures.
Initializes device-side fields including rho, p, c, f, g, and gradients.
Definition at line 895 of file NsAllen.cu.
References clip::Solver::m_DA.
Equilibrium_new()
__device__ __forceinline__ CLIP_REAL clip::NSAllen::Equilibrium_new (const WMRT::WMRTvelSet velSet, CLIP_UINT q, CLIP_REAL Ux, CLIP_REAL Uy, CLIP_REAL Uz = 0) static
Computes equilibrium distribution for a given velocity set.
Computes equilibrium distribution for a given direction and velocity.
Parameters
velSet Lattice velocity set
q Direction index
Ux X-velocity
Uy Y-velocity
Uz Z-velocity (optional, default = 0)
Returns
Equilibrium distribution value
velSet Lattice velocity set q Direction index Ux Local velocity in x-direction Uy Local velocity in y-direction Uz Local velocity in z-direction Equilibrium value for direction q
Definition at line 81 of file NsAllen.cu.
Referenced by clip::kernelCollisionMRTf(), clip::kernelCollisionMRTg(), clip::KernelInitializeDistributions(), and clip::kernelMacroscopicf().
initialCondition()
void clip::NSAllen::initialCondition ()
Sets the initial state of the simulation.
Initializes host-side phase field variable c based on geometry and case type.
Definition at line 766 of file NsAllen.cu.
References clip::InputData::Bubble, clip::InputData::Drop, clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::InputData::Jet, clip::Solver::m_DA, clip::InputData::RTI, and clip::Geometry::sdf().
macroscopic()
void clip::NSAllen::macroscopic ()
Computes macroscopic quantities (rho, u) from distribution functions.
Updates macroscopic fields: density, pressure, velocity, chemical potential, and gradients.
Definition at line 863 of file NsAllen.cu.
References clip::Solver::m_DA.
Referenced by solve().
solve()
void clip::NSAllen::solve ()
(Optional) Placeholder or user-defined inlet structure
Runs one full LBM timestep: collision, boundary conditions, streaming, and macroscopic update.
Main time loop or solution iteration
Definition at line 879 of file NsAllen.cu.
References clip::Solver::m_DA, macroscopic(), and clip::Solver::velocityBoundary().
The documentation for this class was generated from the following files:
/home/runner/work/CLIP/CLIP/include/equation/NsAllen.cuh
/home/runner/work/CLIP/CLIP/src/equation/NsAllen.cu