CLIP: clip::CheckPointer Class Reference
clip::CheckPointer Class Reference
Handles checkpointing for saving and resuming LBM simulations.
Public Member Functions
CheckPointer (DataArray &DA, const InputData &idata, const Domain &domain, TimeInfo &ti, const Boundary &boundary)
Constructs the CheckPointer and links required components.
virtual ~CheckPointer ()
Virtual destructor.
void save ()
Saves the current simulation state to a binary checkpoint folder.
void load ()
Loads simulation state from the latest checkpoint folder.
Detailed Description
Handles checkpointing for saving and resuming LBM simulations.
The CheckPointer class provides functionality to save and load simulation state from binary files, including all primary fields, time step information, and domain size. This enables resuming long simulations without restarting from the beginning.
Definition at line 36 of file CheckPointer.cuh.
Constructor & Destructor Documentation
CheckPointer()
clip::CheckPointer::CheckPointer (DataArray & DA, const InputData & idata, const Domain & domain, TimeInfo & ti, const Boundary & boundary) explicit
Constructs the CheckPointer and links required components.
Parameters
DA Reference to data array manager
idata Reference to simulation input
domain Reference to simulation domain
ti Reference to time-tracking object
boundary Reference to boundary condition data
Definition at line 40 of file CheckPointer.cu.
~CheckPointer()
clip::CheckPointer::~CheckPointer () virtual default
Virtual destructor.
Destructor for CheckPointer.
Member Function Documentation
load()
void clip::CheckPointer::load ()
Loads simulation state from the latest checkpoint folder.
Loads a previously saved checkpoint from disk and restores simulation state.
Definition at line 84 of file CheckPointer.cu.
References clip::Boundary::isFreeConvect, and clip::Logger::Success().
save()
void clip::CheckPointer::save ()
Saves the current simulation state to a binary checkpoint folder.
Saves the current simulation state to disk if checkpointing is enabled and interval is reached.
Definition at line 53 of file CheckPointer.cu.
References clip::TimeInfo::getCurrentStep(), clip::Boundary::isFreeConvect, clip::InputData::params, and clip::Logger::Success().
The documentation for this class was generated from the following files:
/home/runner/work/CLIP/CLIP/include/io/CheckPointer.cuh
/home/runner/work/CLIP/CLIP/src/io/CheckPointer.cu