CLIP: clip::Geometry Class Reference
clip::Geometry Class Reference
Represents one or more geometric objects for level-set-based boundary embedding.
Classes
struct Entry
Represents a user-defined geometric object in host memory.
struct GeometryDevice
Device-side flattened structure storing all geometry info used in kernels.
Public Types
enum class Type {
Circle = 0 , Sphere = 1 , Square = 2 , Cube = 3 ,
Perturbation = 4 , Unknown = 5 , MAX = 6
}
Enumeration of supported geometric object types.
Public Member Functions
Geometry (const InputData &idata)
Constructs the Geometry manager using simulation input parameters.
~Geometry ()
Destructor.
const GeometryDevice & getDeviceStruct () const
Returns the device-side structure containing all geometry data.
void print () const
Prints all geometry entries for debug or verification.
Static Public Member Functions
__device__ __host__ static CLIP_REAL sdf (const GeometryDevice &geo, CLIP_INT id, CLIP_REAL x, CLIP_REAL y, CLIP_REAL z)
Evaluates the signed distance function (SDF) to a given object at a spatial location.
Detailed Description
Represents one or more geometric objects for level-set-based boundary embedding.
The Geometry class handles reading, storing, and evaluating geometric objects like spheres, cubes, and perturbed interfaces. It generates a device-accessible structure used by the solver for computing signed distance functions (SDF) to these shapes.
Definition at line 39 of file Geometry.cuh.
Member Enumeration Documentation
Type
enum class clip::Geometry::Type strong
Enumeration of supported geometric object types.
Definition at line 54 of file Geometry.cuh.
Constructor & Destructor Documentation
Geometry()
clip::Geometry::Geometry (const InputData & idata) explicit
Constructs the Geometry manager using simulation input parameters.
Parameters
idata Reference to input configuration
Definition at line 50 of file Geometry.cu.
References clip::Logger::Info(), print(), and clip::Logger::Success().
~Geometry()
clip::Geometry::~Geometry ()
Destructor.
Default destructor for Geometry.
Definition at line 63 of file Geometry.cu.
Member Function Documentation
getDeviceStruct()
const GeometryDevice & clip::Geometry::getDeviceStruct () const inline
Returns the device-side structure containing all geometry data.
Definition at line 166 of file Geometry.cuh.
Referenced by clip::NSAllen::NSAllen(), and clip::Solver::Solver().
print()
void clip::Geometry::print () const
Prints all geometry entries for debug or verification.
Prints the parsed geometry list to standard output.
Definition at line 276 of file Geometry.cu.
Referenced by Geometry().
sdf()
__device__ __host__ static CLIP_REAL clip::Geometry::sdf (const GeometryDevice & geo, CLIP_INT id, CLIP_REAL x, CLIP_REAL y, CLIP_REAL z) inline static
Evaluates the signed distance function (SDF) to a given object at a spatial location.
Parameters
geo Reference to device geometry pool
id Geometry ID to match
x X-coordinate
y Y-coordinate
z Z-coordinate
Returns
Signed distance (positive = outside, negative = inside)
Definition at line 102 of file Geometry.cuh.
References IDX_X, IDX_Y, and IDX_Z.
Referenced by clip::NSAllen::initialCondition(), and clip::JetBoundary().
The documentation for this class was generated from the following files:
/home/runner/work/CLIP/CLIP/include/geometry/Geometry.cuh
/home/runner/work/CLIP/CLIP/src/geometry/Geometry.cu