CLIP: clip::InputData Class Reference
clip::InputData Class Reference
Reads simulation parameters from a configuration file and stores them in a structured format.
Classes
struct SimParams
Struct holding all simulation parameters, parsed from input.
Public Types
enum CaseType {
Bubble = 0 , Drop = 1 , RTI = 2 , Jet = 3 ,
Unknown = 4
}
Enumerates supported simulation case types.
Public Member Functions
InputData (const std::string &filename="config.txt")
Constructs the InputData object and optionally sets the config file path.
void read_config ()
Parses the configuration file and fills the SimParams structure.
std::string getConfig () const
Returns the filename used for the configuration file.
Public Attributes
SimParams params
Public simulation parameters populated from the config file.
Detailed Description
Reads simulation parameters from a configuration file and stores them in a structured format.
The InputData class parses a plain text config file and populates all required physical and numerical parameters for the CLIP simulation. It supports scalar values, arrays, enums, and vector fields.
Definition at line 37 of file InputData.cuh.
Member Enumeration Documentation
CaseType
enum clip::InputData::CaseType
Enumerates supported simulation case types.
Enumerator
Bubble
Rising or stationary bubble.
Drop
Falling or stationary drop.
RTI
Rayleigh–Taylor instability.
Jet
Liquid jet simulation.
Unknown
Unknown or unspecified case.
Definition at line 56 of file InputData.cuh.
Constructor & Destructor Documentation
InputData()
clip::InputData::InputData (const std::string & filename = "config.txt") explicit
Constructs the InputData object and optionally sets the config file path.
Constructs an InputData object and loads simulation parameters from a config file.
Parameters
filename Configuration file (default: "config.txt")
filename Path to the configuration file
Definition at line 43 of file InputData.cu.
References clip::Logger::Info(), read_config(), and clip::Logger::Success().
Member Function Documentation
getConfig()
std::string clip::InputData::getConfig () const
Returns the filename used for the configuration file.
Returns the path to the currently loaded config file.
Returns
File path as a string
Definition at line 432 of file InputData.cu.
read_config()
void clip::InputData::read_config ()
Parses the configuration file and fills the SimParams structure.
Reads all simulation parameters from the config file and fills the params structure.
Initializes derived quantities based on the selected case type (e.g., Drop, Bubble, RTI, Jet), including muH, muL, sigma, tauH, tauL, and phase-field constants.
Definition at line 57 of file InputData.cu.
References Bubble, Drop, IDX_Y, Jet, params, and RTI.
Referenced by InputData().
Member Data Documentation
params
SimParams clip::InputData::params
Public simulation parameters populated from the config file.
Definition at line 119 of file InputData.cuh.
Referenced by clip::Domain::Domain(), clip::TimeInfo::getFinalStep(), clip::NSAllen::NSAllen(), clip::Reporter::print(), read_config(), clip::CheckPointer::save(), and clip::VTSwriter::writeToFile().
The documentation for this class was generated from the following files:
/home/runner/work/CLIP/CLIP/include/input/InputData.cuh
/home/runner/work/CLIP/CLIP/src/input/InputData.cu