CLIP: /home/runner/work/CLIP/CLIP/src/equation/NsAllen.cu File Reference
NsAllen.cu File Reference
Implementation of a two-phase Lattice Boltzmann Method (LBM) solver using the Allen–Cahn phase-field model.
#include <NsAllen.cuh>
#include <Solver.cuh>
Functions
__global__ void clip::KernelInitializeDistributions (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, const Domain::DomainInfo domain, CLIP_REAL *dev_f, CLIP_REAL *dev_g, CLIP_REAL *dev_f_post, CLIP_REAL *dev_g_post, CLIP_REAL *dev_c, CLIP_REAL *dev_rho, CLIP_REAL *dev_p, CLIP_REAL *dev_vel, CLIP_REAL *dev_normal)
Initializes device-side distributions, density, pressure, velocity, and normals.
__global__ void clip::Chemical_Potential (const InputData::SimParams params, const Domain::DomainInfo domain, double *dev_c, double *dev_mu)
Computes chemical potential from current phase field using Allen–Cahn model.
__global__ void clip::normal_FD (const Domain::DomainInfo domain, CLIP_REAL *dev_dc, CLIP_REAL *dev_normal)
Computes normalized interface normals using finite difference of c.
__global__ void clip::Isotropic_Gradient (const Domain::DomainInfo domain, CLIP_REAL *dev_c, CLIP_REAL *dev_dc)
Computes isotropic central difference gradient of phase field c.
__global__ void clip::kernelStreaming (const WMRT::WMRTvelSet velSet, const Domain::DomainInfo domain, CLIP_REAL *f, CLIP_REAL *f_post)
Streams lattice values from neighboring nodes to current node for f or g.
__global__ void clip::kernelMacroscopicf (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, const Domain::DomainInfo domain, CLIP_REAL *dev_p, CLIP_REAL *dev_rho, CLIP_REAL *dev_c, CLIP_REAL *dev_f_post, CLIP_REAL *dev_dc, CLIP_REAL *dev_vel, CLIP_REAL *dev_mu)
Computes macroscopic velocity and pressure from f_post, including body forces.
__global__ void clip::kernelMacroscopicg (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, const Domain::DomainInfo domain, CLIP_REAL *dev_g_post, CLIP_REAL *dev_rho, CLIP_REAL *dev_c)
Computes phase field c and density rho from g_post.
__global__ void clip::kernelCollisionMRTg (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, const Domain::DomainInfo domain, CLIP_REAL *dev_g, CLIP_REAL *dev_g_post, CLIP_REAL *dev_c, CLIP_REAL *dev_rho, CLIP_REAL *dev_vel, CLIP_REAL *dev_normal)
Applies MRT collision operator for phase field distribution g.
__global__ void clip::kernelCollisionMRTf (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, const Domain::DomainInfo domain, CLIP_REAL *dev_f, CLIP_REAL *dev_f_post, CLIP_REAL *dev_p, CLIP_REAL *dev_c, CLIP_REAL *dev_dc, CLIP_REAL *dev_mu, CLIP_REAL *dev_rho, CLIP_REAL *dev_vel, CLIP_REAL *dev_normal)
Applies MRT collision operator for momentum distribution f, including force correction.
Detailed Description
Implementation of a two-phase Lattice Boltzmann Method (LBM) solver using the Allen–Cahn phase-field model.
This file contains the CUDA kernels and host-side logic for simulating interfacial flows such as bubbles, drops, jets, and Rayleigh–Taylor instability using the weighted MRT collision operator.
Author
Mehdi
Date
2025
The solver supports:
Phase-field Allen–Cahn interface tracking
Gravity and capillary forces
Variable viscosity and density
Free-convective, wall, slip, Neumann, and periodic boundaries
MRT-based force coupling
Conservative mass-preserving Allen–Cahn scheme
Key Components:
initialCondition() initializes c based on geometry.
deviceInitializer() prepares initial fields like rho, mu, vel, etc.
solve() runs one LBM time step with streaming, collision, and BCs.
collision(), streaming(), and macroscopic() implement core solver steps.
CUDA kernels implement equilibrium computation, force coupling, gradients, and chemical potential.
Assumes usage of compile-time macros: ENABLE_2D or ENABLE_3D, and user-defined InputData, Boundary, Geometry, Domain, and DataArray classes.
Definition in file NsAllen.cu.
Function Documentation
Chemical_Potential()
__global__ void clip::Chemical_Potential (const InputData::SimParams params, const Domain::DomainInfo domain, double * dev_c, double * dev_mu)
Computes chemical potential from current phase field using Allen–Cahn model.
Definition at line 212 of file NsAllen.cu.
References clip::Chemical_Potential(), clip::Domain::getIndex(), and THREAD_IDX_X.
Referenced by clip::Chemical_Potential().
Isotropic_Gradient()
__global__ void clip::Isotropic_Gradient (const Domain::DomainInfo domain, CLIP_REAL * dev_c, CLIP_REAL * dev_dc)
Computes isotropic central difference gradient of phase field c.
Definition at line 285 of file NsAllen.cu.
References clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::Isotropic_Gradient(), and THREAD_IDX_X.
Referenced by clip::Isotropic_Gradient().
kernelCollisionMRTf()
__global__ void clip::kernelCollisionMRTf (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, const Domain::DomainInfo domain, CLIP_REAL * dev_f, CLIP_REAL * dev_f_post, CLIP_REAL * dev_p, CLIP_REAL * dev_c, CLIP_REAL * dev_dc, CLIP_REAL * dev_mu, CLIP_REAL * dev_rho, CLIP_REAL * dev_vel, CLIP_REAL * dev_normal)
Applies MRT collision operator for momentum distribution f, including force correction.
Definition at line 590 of file NsAllen.cu.
References clip::InputData::Bubble, clip::WMRT::convertD2Q9Weighted(), clip::WMRT::convertD3Q19Weighted(), clip::InputData::Drop, clip::NSAllen::Equilibrium_new(), clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::kernelCollisionMRTf(), clip::WMRT::reconvertD2Q9Weighted(), clip::WMRT::reconvertD3Q19Weighted(), clip::InputData::RTI, and THREAD_IDX_X.
Referenced by clip::kernelCollisionMRTf().
kernelCollisionMRTg()
__global__ void clip::kernelCollisionMRTg (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, const Domain::DomainInfo domain, CLIP_REAL * dev_g, CLIP_REAL * dev_g_post, CLIP_REAL * dev_c, CLIP_REAL * dev_rho, CLIP_REAL * dev_vel, CLIP_REAL * dev_normal)
Applies MRT collision operator for phase field distribution g.
Definition at line 546 of file NsAllen.cu.
References clip::NSAllen::Equilibrium_new(), clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::kernelCollisionMRTg(), and THREAD_IDX_X.
Referenced by clip::kernelCollisionMRTg().
KernelInitializeDistributions()
__global__ void clip::KernelInitializeDistributions (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, const Domain::DomainInfo domain, CLIP_REAL * dev_f, CLIP_REAL * dev_g, CLIP_REAL * dev_f_post, CLIP_REAL * dev_g_post, CLIP_REAL * dev_c, CLIP_REAL * dev_rho, CLIP_REAL * dev_p, CLIP_REAL * dev_vel, CLIP_REAL * dev_normal)
Initializes device-side distributions, density, pressure, velocity, and normals.
Definition at line 141 of file NsAllen.cu.
References clip::InputData::Bubble, clip::InputData::Drop, clip::NSAllen::Equilibrium_new(), clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::KernelInitializeDistributions(), and THREAD_IDX_X.
Referenced by clip::KernelInitializeDistributions().
kernelMacroscopicf()
__global__ void clip::kernelMacroscopicf (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, const Domain::DomainInfo domain, CLIP_REAL * dev_p, CLIP_REAL * dev_rho, CLIP_REAL * dev_c, CLIP_REAL * dev_f_post, CLIP_REAL * dev_dc, CLIP_REAL * dev_vel, CLIP_REAL * dev_mu)
Computes macroscopic velocity and pressure from f_post, including body forces.
Definition at line 374 of file NsAllen.cu.
References clip::InputData::Bubble, clip::WMRT::convertD2Q9Weighted(), clip::WMRT::convertD3Q19Weighted(), clip::InputData::Drop, clip::NSAllen::Equilibrium_new(), clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::kernelMacroscopicf(), clip::WMRT::reconvertD2Q9Weighted(), clip::WMRT::reconvertD3Q19Weighted(), clip::InputData::RTI, and THREAD_IDX_X.
Referenced by clip::kernelMacroscopicf().
kernelMacroscopicg()
__global__ void clip::kernelMacroscopicg (const WMRT::WMRTvelSet velSet, const InputData::SimParams params, const Domain::DomainInfo domain, CLIP_REAL * dev_g_post, CLIP_REAL * dev_rho, CLIP_REAL * dev_c)
Computes phase field c and density rho from g_post.
Definition at line 517 of file NsAllen.cu.
References clip::Domain::getIndex(), clip::kernelMacroscopicg(), and THREAD_IDX_X.
Referenced by clip::kernelMacroscopicg().
kernelStreaming()
__global__ void clip::kernelStreaming (const WMRT::WMRTvelSet velSet, const Domain::DomainInfo domain, CLIP_REAL * f, CLIP_REAL * f_post)
Streams lattice values from neighboring nodes to current node for f or g.
Definition at line 332 of file NsAllen.cu.
References clip::Domain::getIndex(), clip::kernelStreaming(), and THREAD_IDX_X.
Referenced by clip::kernelStreaming().
normal_FD()
__global__ void clip::normal_FD (const Domain::DomainInfo domain, CLIP_REAL * dev_dc, CLIP_REAL * dev_normal)
Computes normalized interface normals using finite difference of c.
Definition at line 246 of file NsAllen.cu.
References clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::normal_FD(), and THREAD_IDX_X.
Referenced by clip::normal_FD().