CLIP: /home/runner/work/CLIP/CLIP/src/utils/Reporter.cu File Reference
Reporter.cu File Reference
Reporting and diagnostics for CLIP simulations.
#include "Reporter.cuh"
Functions
__global__ void clip::sumReductionKernel (const CLIP_REAL *__restrict__ data, CLIP_REAL *partialSums, Domain::DomainInfo domain)
CUDA kernel for parallel sum reduction over a scalar field.
Detailed Description
Reporting and diagnostics for CLIP simulations.
This file implements the Reporter class used to log and track simulation progress. It includes device and host-side code for computing global quantities (e.g., total concentration). The class prints diagnostics like time step, domain size, and integral of scalar fields at user-defined intervals. It also detects divergence (e.g., NaNs in concentration).
CUDA kernels are used for fast parallel reductions on the device.
Author
Mehdi Shadkhah
Date
2025
Definition in file Reporter.cu.
Function Documentation
sumReductionKernel()
__global__ void clip::sumReductionKernel (const CLIP_REAL *__restrict__ data, CLIP_REAL * partialSums, Domain::DomainInfo domain)
CUDA kernel for parallel sum reduction over a scalar field.
Parameters
data Pointer to device array containing values to be summed.
partialSums Output array for storing per-block partial results.
domain Domain info including ghost zone and extents.
Definition at line 50 of file Reporter.cu.
References clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, and clip::sumReductionKernel().
Referenced by clip::sumReductionKernel().