CLIP: /home/runner/work/CLIP/CLIP/src/solver/Solver.cu File Reference
Solver.cu File Reference
Core LBM solver class with all CUDA boundary condition kernels.
#include <Solver.cuh>
Functions
template<int dof = 1>
__global__ void clip::kernelPeriodicBoundary (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, CLIP_REAL *dev_a, CLIP_REAL *dev_b=nullptr)
Applies periodic boundary conditions in X, Y (and Z if 3D).
template<CLIP_UINT Q, CLIP_UINT dof>
__global__ void clip::kernelFullBouncBack (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, const WMRT::wallBCMap wallBCMap, CLIP_REAL *dev_a, CLIP_REAL *dev_b=nullptr)
Applies full bounce-back for walls (legacy implementation).
template<CLIP_UINT Q, CLIP_UINT dof, typename T >
__global__ void clip::kernelHalfBounceBack (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, const T wallMap, CLIP_REAL *dev_a, CLIP_REAL *dev_a_post, CLIP_REAL *dev_b, CLIP_REAL *dev_b_post)
Applies half-way bounce-back for wall and slip boundaries.
template<CLIP_UINT Q, CLIP_UINT dof, typename T >
__global__ void clip::kernelFreeConvect (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, const T wallMap, CLIP_REAL *dev_vel, CLIP_REAL *dev_a, CLIP_REAL *dev_a_prev, CLIP_REAL *dev_b, CLIP_REAL *dev_b_prev)
Implements free-convective outlet boundary (do-nothing).
template<CLIP_UINT Q, CLIP_UINT dof, typename T >
__global__ void clip::kernelNeumann (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, const T wallMap, CLIP_REAL *dev_a, CLIP_REAL *dev_b)
Applies zero-gradient Neumann boundary conditions.
__global__ void clip::JetBoundary (const Domain::DomainInfo domain, const Geometry::GeometryDevice geom, const Boundary::BCTypeMap BCmap, const WMRT::WMRTvelSet velSet, const WMRT::wallBCMap wallBCMap, CLIP_REAL *dev_c, CLIP_REAL *dev_f, CLIP_REAL *dev_g)
Enforces velocity inlet boundaries using equilibrium-based reflection.
__global__ void clip::kernelMirrorBoundary (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, CLIP_REAL *dev_a)
Applies mirror boundary for scalar fields (copies inner value to ghost).
Detailed Description
Core LBM solver class with all CUDA boundary condition kernels.
This file defines the Solver class and implements the main GPU kernels used in the CLIP framework for handling various boundary conditions in 2D and 3D:
Periodic
Wall (full and half bounce-back)
Slip wall
Neumann (zero-gradient)
Free-convective (natural outflow)
Velocity inlet (e.g., jet)
Mirror (for scalar field extrapolation)
The kernels apply per-boundary updates and are launched inside solver member functions. This file also defines helper methods for launching these kernels conditionally.
Author
Mehdi Shadkhah
Date
2025
Definition in file Solver.cu.
Function Documentation
JetBoundary()
__global__ void clip::JetBoundary (const Domain::DomainInfo domain, const Geometry::GeometryDevice geom, const Boundary::BCTypeMap BCmap, const WMRT::WMRTvelSet velSet, const WMRT::wallBCMap wallBCMap, CLIP_REAL * dev_c, CLIP_REAL * dev_f, CLIP_REAL * dev_g)
Enforces velocity inlet boundaries using equilibrium-based reflection.
Evaluates SDF to restrict application to jet regions. Uses second-order momentum compensation based on target velocity.
XMinus
XPlus
YMinus
YPlus
Definition at line 550 of file Solver.cu.
References clip::Solver::Equilibrium_new(), clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::JetBoundary(), clip::Geometry::sdf(), and THREAD_IDX_X.
Referenced by clip::JetBoundary().
kernelFreeConvect()
template<CLIP_UINT Q, CLIP_UINT dof, typename T > __global__ void clip::kernelFreeConvect (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, const T wallMap, CLIP_REAL * dev_vel, CLIP_REAL * dev_a, CLIP_REAL * dev_a_prev, CLIP_REAL * dev_b, CLIP_REAL * dev_b_prev)
Implements free-convective outlet boundary (do-nothing).
Template Parameters
Q Number of discrete velocities
dof Degrees of freedom
T Wall bounce-back map
Definition at line 343 of file Solver.cu.
References clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::kernelFreeConvect(), and THREAD_IDX_X.
Referenced by clip::kernelFreeConvect().
kernelFullBouncBack()
template<CLIP_UINT Q, CLIP_UINT dof> __global__ void clip::kernelFullBouncBack (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, const WMRT::wallBCMap wallBCMap, CLIP_REAL * dev_a, CLIP_REAL * dev_b = nullptr)
Applies full bounce-back for walls (legacy implementation).
Template Parameters
Q Number of discrete velocities
dof Degrees of freedom
Definition at line 150 of file Solver.cu.
References clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::kernelFullBouncBack(), and THREAD_IDX_X.
Referenced by clip::kernelFullBouncBack().
kernelHalfBounceBack()
template<CLIP_UINT Q, CLIP_UINT dof, typename T > __global__ void clip::kernelHalfBounceBack (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, const T wallMap, CLIP_REAL * dev_a, CLIP_REAL * dev_a_post, CLIP_REAL * dev_b, CLIP_REAL * dev_b_post)
Applies half-way bounce-back for wall and slip boundaries.
Template Parameters
Q Number of discrete velocities
dof Degrees of freedom
T Bounce-back map type (wall/slip)
Definition at line 249 of file Solver.cu.
References clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::kernelHalfBounceBack(), and THREAD_IDX_X.
Referenced by clip::kernelHalfBounceBack().
kernelMirrorBoundary()
__global__ void clip::kernelMirrorBoundary (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, CLIP_REAL * dev_a)
Applies mirror boundary for scalar fields (copies inner value to ghost).
Definition at line 915 of file Solver.cu.
References clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::Boundary::isMirrorType(), clip::kernelMirrorBoundary(), and THREAD_IDX_X.
Referenced by clip::kernelMirrorBoundary().
kernelNeumann()
template<CLIP_UINT Q, CLIP_UINT dof, typename T > __global__ void clip::kernelNeumann (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, const T wallMap, CLIP_REAL * dev_a, CLIP_REAL * dev_b)
Applies zero-gradient Neumann boundary conditions.
Template Parameters
Q Number of discrete velocities
dof Degrees of freedom
T Bounce-back map (typically wallBCMap)
Definition at line 463 of file Solver.cu.
References clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::kernelNeumann(), and THREAD_IDX_X.
Referenced by clip::kernelNeumann().
kernelPeriodicBoundary()
template<int dof = 1> __global__ void clip::kernelPeriodicBoundary (const Domain::DomainInfo domain, const Boundary::BCTypeMap BCmap, CLIP_REAL * dev_a, CLIP_REAL * dev_b = nullptr)
Applies periodic boundary conditions in X, Y (and Z if 3D).
Template Parameters
dof Number of degrees of freedom
Parameters
domain Simulation domain info
BCmap Boundary condition map
dev_a Primary field array
dev_b Optional secondary field (e.g., for MRT collision)
Definition at line 76 of file Solver.cu.
References clip::Domain::getIndex(), IDX_X, IDX_Y, IDX_Z, clip::kernelPeriodicBoundary(), and THREAD_IDX_X.
Referenced by clip::kernelPeriodicBoundary().